# Generated by Django 4.2.11 on 2025-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='error', max_length=30)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
