# Generated by Django 4.2.11 on 2025-04-04 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appareil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appareil',
            old_name='pseudo',
            new_name='marque',
        ),
        migrations.RemoveField(
            model_name='appareil',
            name='age',
        ),
        migrations.AddField(
            model_name='appareil',
            name='connectivite',
            field=models.CharField(choices=[('Wifi', 'Wifi'), ('Deconnecté', 'Deconnecté')], default='error', max_length=20),
        ),
        migrations.AddField(
            model_name='appareil',
            name='etat',
            field=models.CharField(choices=[('Connecté', 'Connecté'), ('Deconnecté', 'Deconnecté')], default='error', max_length=20),
        ),
        migrations.AddField(
            model_name='appareil',
            name='etat_de_batterie',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='appareil',
            name='nom',
            field=models.CharField(default='error', max_length=30),
        ),
        migrations.AddField(
            model_name='appareil',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appareil',
            name='type',
            field=models.CharField(default='error', max_length=30),
        ),
        migrations.AddField(
            model_name='appareil',
            name='volume',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
