# Generated by Django 4.2.11 on 2025-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appareil', '0002_rename_pseudo_appareil_marque_remove_appareil_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='connectivite',
            field=models.CharField(choices=[('Wifi', 'Wifi'), ('Deconnecté', 'Ethernet'), ('error', 'error')], default='error', max_length=20),
        ),
        migrations.AlterField(
            model_name='appareil',
            name='etat',
            field=models.CharField(choices=[('Connecté', 'Connecté'), ('Deconnecté', 'Deconnecté')], default='Deconnecté', max_length=20),
        ),
    ]
