# Generated by Django 4.2.11 on 2025-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appareil', '0004_alter_appareil_connectivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appareil',
            name='connectivite',
            field=models.CharField(choices=[('Wifi', 'Wifi'), ('Ethernet', 'Ethernet')], default='error', max_length=20),
        ),
    ]
