# Generated by Django 5.2 on 2025-04-05 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='error', max_length=200, unique=True)),
                ('pseudo', models.CharField(default='error', max_length=30)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='error', max_length=30)),
                ('date_de_naissance', models.DateField(default='1900-01-01')),
                ('type_de_membre', models.CharField(default='error', max_length=30)),
                ('prenom', models.CharField(default='error', max_length=30)),
                ('nom', models.CharField(default='error', max_length=30)),
                ('mot_de_passe', models.CharField(default='error', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
