# Generated by Django 4.2.11 on 2025-04-04 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='error', max_length=30)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='error', max_length=30)),
                ('date_de_naissance', models.DateField(default='1900-01-01')),
                ('type_de_membre', models.CharField(default='error', max_length=30)),
                ('photo', models.ImageField(default='error', upload_to='')),
                ('prenom', models.CharField(default='error', max_length=30)),
                ('nom', models.CharField(default='error', max_length=30)),
                ('mot_de_passe', models.CharField(default='error', max_length=50)),
            ],
        ),
    ]
