# Generated by Django 4.2.11 on 2025-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(default='error', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('sexe', models.CharField(default='error', max_length=30)),
                ('date_de_naissance', models.DateField(default='1900-01-01')),
                ('type_de_membre', models.CharField(default='error', max_length=30)),
                ('photo', models.ImageField(default='error', upload_to='')),
                ('prenom', models.CharField(default='error', max_length=30)),
                ('nom', models.CharField(default='error', max_length=30)),
                ('mot_de_passe', models.CharField(default='error', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
