# Generated by Django 4.2.11 on 2025-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='email',
            field=models.EmailField(default='error', max_length=200, unique=True),
        ),
    ]
