# Generated by Django 5.2 on 2025-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='mot_de_passe',
            field=models.CharField(default='error', max_length=128),
        ),
    ]
