# Generated by Django 4.2.11 on 2025-04-04 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profil_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], default='error', max_length=30),
        ),
    ]
