# Generated by Django 5.2 on 2025-04-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_alter_profil_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='photo',
        ),
    ]
